#!/usr/local/bin/perl
#
# Expected usage: perl sliceToIm.pl image.png
# Assumes image is located /media/sf_Screenshots/rekognition/
# Also expects a tmp.txt file containing the output from 
# Expected tmp.txt should contain something like this: 
# [(slice(132L, 151L, None), slice(275L, 292L, None)), (slice(156L, 175L, None), slice(310L, 327L, None))]

#use strict;
#use warnings;
#use Data::Dumper qw(Dumper);

# Read in the file generated by subimage-find (tmp.txt) 
my $outfile = "/media/sf_Screenshots/rekognition/". $ARGV[0]. ".png";
if ($outfile eq "" or length($outfile) < 5) {
	die "invalid file input!";
}
my $inTextFilename = "./tmp.txt";
my $content;
open(my $fh, '<', $inTextFilename) or die "cannot open file $inTextFilename";
{
    local $/;
    $content = <$fh>;
}
close($fh);

#print "input was: ". $content;

# How many "slice" did we find?
my $cnt = () = $content =~ /slice/g;
my ($topy, $bottomy, $topx, $bottomx, $ty2, $by2, $tx2, $bx2) = "";

#process input:
if ($cnt > 0) {
	# extract the slices and get the coordinates of the top-left of the selection:
	if ($cnt == 4) {
		($topy, $bottomy, $topx, $bottomx, $ty2, $by2, $tx2, $bx2) = $content =~ /slice\((\d+).*?(\d+).*?slice\((\d+).*?(\d+).*?slice\((\d+).*?(\d+).*?slice\((\d+).*?(\d+).*/g;
	} elsif ($cnt == 2) {
		($topy, $bottomy, $topx, $bottomx) = $content =~ /slice\((\d+).*?(\d+).*?slice\((\d+).*?(\d+).*?/g;
	} else {
		print "no match";
	}

	# now convert using the coordinates we extracted:
	# example command:
	# convert /media/sf_Screenshots/rekognition/Bridgewatch-1.bmp.png assets/replaceChange.png -geometry +310+156 -composite $file
	my $command = "convert ". $outfile. " assets/replaceChange.png -geometry +". $topx. "+". $topy. " -composite ". $outfile;
	#print "$command\n";
	`$command`;

	if ($tx2 ne "") {
		$command = "convert ". $outfile. " assets/replaceChange.png -geometry +". $tx2. "+". $ty2. " -composite ". $outfile;
		#print "$command\n";
		`$command`;
	}
	print "Hid silvers on $outfile.\n";
}
